on:
  pull_request:
    branches:    
      - master
jobs:   
  comment:
    name: Adding comment on Pull Request
    runs-on: macos-latest
    steps:
      - name: Add comment to PR
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $URL
          eventMatrix = github.event
          echo $eventMatrix
